server:
  port: 8223

spring:
  application:
    name: config-server
  profiles:
    active: composite
  cloud:
    config:
      server:
        composite:
          -
            type: couchbase
            connectionString: couchbase://127.0.0.1
            userName: userName1
            password: Password1
            configBucketName: configuration-store
            collectionName: application-properties
            scope: technical
            order: 1
          - type: git
            uri: https://github.com/santhosh34/spring-cloud-config-store.git
            search-paths:
              - '{application}/{profile}'
            order: 2
    bus:
      enabled:  true
      id: my-config-server
      destination: myownmanuallycreatedtopic
    stream:
      kafka:
        binder:
          autoCreateTopics: false
          zkNodes:  localhost:2181
          brokers: localhost:29092
          consumer-properties:
            allow:
              auto:
                create:
                  topics: false
management:
  endpoints:
    web:
      exposure:
        include:  health, busrefresh, bus-env, refresh, env
  endpoint:
    info:
      enabled: true
logging:
  level:
    ROOT: ERROR
    com.sannette.eis.mega.*: INFO
    org.apache.kafka.*: INFO
